services:
  backend:
    build: .
    container_name: fast-dlp
    ports:
      - "8000:8000"
    volumes:
      - downloads:/app/downloads
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  downloads:
